### ISSUE TITLE
porblem about package import "from _walker import random_walks as _random_walks"

### ISSUE THREAD

**Issue by csjiezhao** [sonout/TrajRNE#1]
I noticed your import the package `_walker` in the `generate_train_data.py`, but I didn't find where the `_walker` is defined. Can you tell me more about it?

**Comment by sonout** [comment]
Sure, you need to install the graph-walker library. See here: https://github.com/kerighan/graph-walker 
I think after that it should already work. If not feel free to ask and I will look into it. Or if you run into any other issues.

**Comment by csjiezhao** [comment]
> Sure, you need to install the graph-walker library. See here: https://github.com/kerighan/graph-walker I think after that it should already work. If not feel free to ask and I will look into it. Or if you run into any other issues.

Thanks for your reply. It works after I installed the lib `graph-walker`. And I have another question, that is, how do I prepare the files `road_segment_map_sample.csv` and `speed_features_unnormalized.csv`  based on myself trajectory data?

**Comment by sonout** [comment]
I added the preprocessing script for porto dataset. If you adjust it to how your data looks, you should be able to preprocess it correctly. Specifically, we preprocessed the data and map matched it using FastMapMatching. Afterward, to obtain speed_features_unnormalized.csv you need to use the function generate_speed_features() in trajectory.py. Hope this helps.
